# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/src/Eppie.App/"                    # Path to '*.sln' directory
    schedule:
      interval: "daily"
    reviewers:
      - "al-kau"
      - "ValeraFinebits"
      - "anatolse"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      UnoPlatform:
        patterns:
          - "Uno.*"
      Microsoft:
        patterns:
          - "Microsoft.*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"                                  # Path to '.gitmodules' directory
    schedule:
      interval: "daily"
    reviewers:
      - "al-kau"
      - "ValeraFinebits"
      - "anatolse"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      submodules:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"                                  # Workflow files stored in the default location
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependencies"
    reviewers:
      - "al-kau"
      - "anatolse"
      - "ValeraFinebits"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      Common-actions:
        patterns:
          - "actions/*"
      Finebits-actions:
        patterns:
          - "finebits/*"
      GitHub-actions:
        patterns:
          - "github/*"
