changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: '💥 Breaking Changes'
      labels:
        - 'type/breaking-change'
    - title: '✨ New Features'
      labels:
        - 'type/feature'
    - title: '🐞 Bug Fixes'
      labels:
        - 'type/fix'
    - title: '🚀 Performance Improvements'
      labels:
        - 'type/performance'
    - title: '🌍 Localization Changes'
      labels:
        - 'type/localization'
