name: '✨ Feature Request'
title: '[FEATURE] <title>'
description: 'Suggest an idea for this project'
labels: ['kind/enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feature request. Please describe the feature in detail, why it would be useful, and what use cases it supports.

  - type: textarea
    attributes:
      label: What Would You Like to Be Added?
      description: A clear description of what you want to happen. Feel free to add any diagrams, (mocked up) screenshots, or other materials that support your story.
      placeholder: I would love to have a button that I can make shiny. This is something that is supported on all the underlaying platforms.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is This Needed?
      description: How would this feature be useful to you or others? Please explain the use case.
      placeholder: I have a situation where I would really want a shiny button to make it stand out from the rest of the plain and boring buttons.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Is there anything else we should know?
    validations:
      required: false
