name: '✍️ New Task'
description: 'Describe a task that needs to be done'
title: '[Task] <title>'
type: Task
labels: ['kind/task']
body:
  - type: markdown
    attributes:
      value: '## Creating a Task'
  - type: markdown
    attributes:
      value: |
        This form should only be used by team members, otherwise please submit a bug report or feature request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: Please list the steps and actions that need to be done.
      placeholder: |
        - [ ] step #1
        - [ ] step #2 @user
        - [ ] step 3
      value: Steps are not defined.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Is There Anything Else We Should Know?
      placeholder: Add any other context or information about the task here. Links or related tasks are welcome.
