################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

---

name: Install Eppie Prerequisites

inputs:
  uno-platform:
    type: boolean
    default: false

  msbuild:
    type: boolean
    default: false

  global-json:
    type: string
    default: './src/Eppie.App/global.json'

  workload-config:
    type: string
    default: './.github/configurations/workload.json'

runs:
  using: "composite"

  steps:
    - name: Setup msbuild
      if: inputs.msbuild == 'true'
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

    - name: Copy global.json
      if: inputs.uno-platform == 'true'
      shell: bash
      run: cp ${{ inputs.global-json }} global.json

    - name: Setup .NET
      if: inputs.uno-platform == 'true'
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
      with:
        global-json-file: global.json

    - name: Select Workload config
      if: inputs.uno-platform == 'true'
      id: workload-config
      uses: finebits/github-actions/toolset/select-configuration@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0
      with:
        json-file: ${{ inputs.workload-config }}
        keywords: ${{ runner.os }}

    - name: Install Workload
      if: inputs.uno-platform == 'true'
      shell: bash
      run: |
        ids="${{ fromJson(steps.workload-config.outputs.config-json)[0].workload-ids }}"
        dotnet workload install $ids --source "https://api.nuget.org/v3/index.json"

    - name: Setup the Uno Platform
      if: inputs.uno-platform == 'true'
      uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0
      with:
        uno-check-manifest: https://raw.githubusercontent.com/unoplatform/uno.check/95904fd037afa7714b695716dddfc5f4c2acf138/manifests/uno.ui.manifest.json  # "DOTNET_SDK_VERSION": "8.0.401"
