###############################################################################
#
#   Copyright 2024 Eppie(https://eppie.io)
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
###############################################################################

---

name: "Build solution"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

jobs:

  prepare:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.build-config.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: config
        id: build-config
        uses: finebits/github-actions/toolset/select-configuration@6fdb3f66a81cb4c285a41ae140b47ab3c5eb4864 # v1.6.0-prerelease
        with:
          json-file: ./.github/configurations/build.json
          keywords: "all"

  build:

    needs: prepare
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    env:
      configuration: ${{ matrix.configuration }}
      target: ${{ matrix.target }}

      dotnet-version: '8.x'

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Setup msbuild
        if: matrix.prerequisites.msbuild == 'true'
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Setup the Uno Platform
        if: matrix.prerequisites.uno-platform == 'true'
        uses: finebits/github-actions/devhub/uno-platform/setup@6fdb3f66a81cb4c285a41ae140b47ab3c5eb4864 # v1.6.0-prerelease

      - name: Build via dotnet
        if: matrix.build.tool == 'dotnet'
        shell: bash
        run: |
          project=${{ matrix.project }}
          configuration=${{ matrix.build.configuration }}
          extra_options=${{ matrix.build.extra }}

          dotnet build --configuration=$configuration $extra_options $project

      - name: Build via msbuild
        if: matrix.build.tool == 'msbuild' && runner.os == 'Windows'
        shell: pwsh
        run: |
          $project=${{ matrix.project }}
          $configuration=${{ matrix.build.configuration }}
          $extra_options=${{ matrix.build.extra }}

          msbuild --target:Rebuild -restore:True -property:Configuration=$configuration $extra_options $project
