################################################################################
#                                                                              #
#   Copyright 2025 Eppie(https://eppie.io)                                     #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

---

name: Publish Desktop [app]

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      architecture:
        type: choice
        default: all
        options:
          - all
          - arm64
          - x64
      dotnet-verbosity:
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic
  workflow_call:
    inputs:
      architecture:
        type: string
        required: true
      dotnet-verbosity:
        type: string
        required: true

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.publish-config.outputs.matrix }}
      interrupt-publication: ${{ steps.publish-config.outputs.is-empty }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Read the macos app publication configuration
        id: publish-config
        uses: finebits/github-actions/toolset/select-configuration@39ec051fda4f00ab2ac5ffb6336ab0ea1ad9ad0f # v3.0.0
        with:
          json-file: ./.github/configurations/publish-desktop-app.json
          keywords: |
            macos
            ${{ inputs.architecture }}

  publish:
    name: Publish ${{ matrix.publish.framework }} ${{ matrix.publish.runtime }}
    needs: prepare
    if: needs.prepare.outputs.interrupt-publication == 'false'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    env:
      publish-path: './.publish/${{ matrix.publish.configuration }}/${{ matrix.publish.framework }}/${{ matrix.publish.runtime }}'
      artifacts-path: './.artifacts/${{ matrix.publish.configuration }}/${{ matrix.publish.framework }}/${{ matrix.publish.runtime }}'

    steps:
      - name: Support longpaths
        if: ${{ runner.os == 'Windows'}}
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Prerequisites
        uses: ./.github/actions/install-prerequisites
        with:
          uno-platform: true

      - name: Import certificate
        run: |
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" publish.keychain
          security default-keychain -s publish.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" publish.keychain

          echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k publish.keychain -P "${{ secrets.MACOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign

          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" publish.keychain
  
          xcrun notarytool store-credentials "NOTARYTOOL_PROFILE" --apple-id "${{ secrets.APPLE_ID }}" --team-id ${{ secrets.TEAM_ID }} --password "${{ secrets.NOTARYTOOL_SPECIFIC_PASSWORD }}"


      - name: Assign version
        id: assign-version
        uses: ./.github/actions/assign-version

      - uses: finebits/github-actions/toolset/file/replace-text@39ec051fda4f00ab2ac5ffb6336ab0ea1ad9ad0f # v3.0.0
        with:
          file: ./src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
          find-what: '\"<Gmail-ClientId>\"'
          replace-with: "${{ secrets.GMAIL_CLIENT_ID }}"

      - uses: finebits/github-actions/toolset/file/replace-text@39ec051fda4f00ab2ac5ffb6336ab0ea1ad9ad0f # v3.0.0
        with:
          file: ./src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
          find-what: '\"<Gmail-ClientSecret>\"'
          replace-with: "${{ secrets.GMAIL_CLIENT_SECRET }}"

      - uses: finebits/github-actions/toolset/file/replace-text@39ec051fda4f00ab2ac5ffb6336ab0ea1ad9ad0f # v3.0.0
        with:
          file: ./src/Eppie.App/Eppie.App.Shared/Authorization/AuthConfig.Uno.cs
          find-what: '\"<Outlook-ClientId>\"'
          replace-with: "${{ secrets.OUTLOOK_CLIENT_ID }}"

      - name: Prepare
        if: matrix.publish.tool == 'dotnet'
        shell: bash
        run: |
          semantic_version='${{ steps.assign-version.outputs.semantic-version }}'
          numeric_version='${{ steps.assign-version.outputs.numeric-version }}'
          app_version='${{ steps.assign-version.outputs.app-version }}'
          app_display_version='${{ steps.assign-version.outputs.app-display-version }}'

          project='${{ matrix.publish.project }}'
          configuration='${{ matrix.publish.configuration }}'
          framework='${{ matrix.publish.framework }}'
          runtime='${{ matrix.publish.runtime }}'
          publish_path='${{ env.publish-path }}'

          prepare='${{ join(matrix.publish.prepare, '|') }}'

          IFS_CACHE=$IFS
          IFS='|'

          options="--configuration=$configuration --framework=$framework --runtime=$runtime"
          version_options="--property:Version=\"$semantic_version\" --property:AssemblyVersion=\"$numeric_version\" --property:PackageVersion=\"$numeric_version\" --property:ApplicationVersion=\"$app_version\" --property:ApplicationDisplayVersion=\"$app_display_version\""
          verbosity_option="--verbosity=${{ inputs.dotnet-verbosity }}"
          for prepare_options in $prepare
          do
            echo "$prepare_options $options $version_options $verbosity_option" | xargs dotnet build $project
          done

          IFS=$IFS_CACHE

      - name: Publish
        if: matrix.publish.tool == 'dotnet'
        shell: bash
        run: |
          semantic_version='${{ steps.assign-version.outputs.semantic-version }}'
          numeric_version='${{ steps.assign-version.outputs.numeric-version }}'
          app_version='${{ steps.assign-version.outputs.app-version }}'
          app_display_version='${{ steps.assign-version.outputs.app-display-version }}'

          project='${{ matrix.publish.project }}'
          configuration='${{ matrix.publish.configuration }}'
          framework='${{ matrix.publish.framework }}'
          runtime='${{ matrix.publish.runtime }}'
          publish_path='${{ env.publish-path }}'
          extra_options='${{ matrix.publish.extra }}'

          options="--output=$publish_path --configuration=$configuration --framework=$framework --runtime=$runtime -property:CodesignKey=\"${{ secrets.DEVELOPER_ID_APPLICATION }}\""
          version_options="--property:Version=\"$semantic_version\" --property:AssemblyVersion=\"$numeric_version\" --property:PackageVersion=\"$numeric_version\" --property:ApplicationVersion=\"$app_version\" --property:ApplicationDisplayVersion=\"$app_display_version\""
          verbosity_option="--verbosity=${{ inputs.dotnet-verbosity }}"
          echo "$options $extra_options $version_options $verbosity_option" | xargs dotnet publish $project 

      - name: Notarization 
        run: |
          publish_path='${{ env.publish-path }}'
          runtime='${{ matrix.publish.runtime }}'
          app_path='${{ env.publish-path }}/Eppie.app'
          bundle_path="${{ env.publish-path }}/Eppie-$runtime.app.zip"

          # zip bundle
          ditto -c -k --sequesterRsrc --keepParent "$app_path" "$bundle_path"
          
          xcrun notarytool submit "$bundle_path" --wait --keychain-profile "NOTARYTOOL_PROFILE"
          xcrun stapler staple "$app_path"

      - name: Prepare Artifacts
        shell: bash
        run: |
          artifact_path="${{ env.artifacts-path }}"
          publish_path="${{ env.publish-path }}"
          tool='${{ matrix.artifact.tool }}'

          mkdir -p "$artifact_path"

          if [[ "$tool" == "cp" ]]; then
            cp -r $publish_path/*.zip ${artifact_path}/ && echo "Copying of the artifact has been completed successfully." || echo "::warning::Failed to copy artifact"
          else
            echo "::warning::Unknown artifact tool: '$tool'"
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Eppie.Desktop-${{ matrix.publish.runtime }} [${{ steps.assign-version.outputs.artifact-version }}]
          path: ${{ env.artifacts-path }}
